---
excluded_methods: 
  #- get_all_feature_flags
  #- list_all_matching_resources
  - "filters_apps_by_guids,_names,_spaces,_and_organizations"
  - "upload_bits_for_a_package_of_type_bits"
  - "upload_the_bits_for_an_admin_buildpack"
classes:
  App:
    - creating_an_app
    - list_all_apps
  Job:
    - retrieve_job_that_was_successful
    - retrieve_job_with_known_failure
    - retrieve_job_with_unknown_failure
    - retrieve_job_that_is_queued
